import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AccesibilityButton from "@/app/components/AccesibilityButton";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "CommunityFix",
  description: "Generated by FirmwareForce",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <AccesibilityButton />
          <Toaster position="top-right" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
