spring.application.name=FirmwareForceBackEnd
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/FirmwareForce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:FirmwareForce}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
app.jwt.secret=${APP_JWT_SECRET:12ehewhfshdgpishipghewipheiph4wip5803y08hihoihougduoaguuHPHOPHIPHPI}
