spring.application.name=FirmwareForceBackEnd
spring.datasource.url=jdbc:postgresql://localhost:5432/FirmwareForce
spring.datasource.username=postgres
spring.datasource.password=FirmwareForce
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always